# Generated by Django 5.0.2 on 2024-02-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_products_active_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerBehav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
    ]
